server:
  port: 8087

spring:
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      database: ecommerce
      username: admin
      password: admin
      authentication-database: admin
      port: 27019
      host: localhost
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

ecommerce:
  broker:
    exchange:
      orderProductCommand: order-product
      orderPaymentCommand: order-payment
      userEvent: ecommerce-userevent
    queue:
      orderProductReply: order-product-reply
      orderPaymentReply: order-payment-reply
      userEvent: order-user-event
    key:
      bindOrderProductRequestCommand: order-product-request
      bindOrderPaymentRequestCommand: order-payment-request
      bindOrderProductReplyCommand: order-product-reply
      bindOrderPaymentReplyCommand: order-payment-reply
